### ISSUE TITLE
When I press any keybins I get an error Mpv v0.38.0

### ISSUE THREAD

**Issue by ArmoryFou** [ZXY101/mpv-jimaku#2]
![image](https://github.com/user-attachments/assets/4673981c-1f84-47e5-9c69-596416c46e67)

**Comment by ArmoryFou** [comment]
This only happens when the script finds the subtitles, if it doesn't find them just shows "no results"

**Comment by ZXY101** [comment]
Which version of the script are you using?

**Comment by ArmoryFou** [comment]
v0.0.3

**Comment by ArmoryFou** [comment]
Yeah, I just read the specifications in the version, I downloaded v0.0.2 and it worked perfectly, sorry.
